name: snap_layouts
description: "A plugin provides a simple window layout button which can implement the native Windows 11 Snap Layouts feature."
version: 0.3.0
homepage: https://github.com/PleaseDont/snap_layouts

platforms:
  windows:

topics:
  - window
  - desktop-window
  - title-bar
  - window-caption
  - snap-layouts

environment:
  sdk: ^3.7.2
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  window_manager: ^0.5.0

dev_dependencies:
  flutter_lints: ^6.0.0
  
flutter:
  plugin:
    platforms:
      windows:
        pluginClass: SnapLayoutsPlugin
